version: '3'

services:
  producer:
    build: ./producer
    ports:
      - '8000:8000'
    env_file:
      - .env
    environment:
      - PORT=8000
    volumes:
      - ./producer:/usr/app

  consumer:
    build: ./consumer
    ports:
      - '8001:8001'
    env_file:
      - .env
    environment:
      - PORT=8001
    volumes:
      - ./consumer:/usr/app